### ISSUE TITLE
Support for “Solution Style” `tsconfig.json` Files

### ISSUE THREAD

**Issue by sodatea** [dominikg/tsconfck#2]
**Describe the feature**

TypeScript 3.9 adds this feature called “Solution Style” `tsconfig.json` https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files

In this case, the actual `tsconfig` may reside in files named not exactly as `tsconfig.json`. The found `tsconfig.json` is only a "solution" file that references other configuration files.

**A Usecase**

Some large full-stack repositories may use it. Those who put `.spec.ts` files alongside the source files may need it too.

**Alternatives**

Not sure whether this feature should be implemented in this package, or in a separate package.

If we're to support this feature, all [top-level options in `tsconfig.json`](https://www.typescriptlang.org/tsconfig) need to be processed, including `files`, `overwrites`, `include`, `exclude` and `references`.

**Additional context**

N/A

**Comment by dominikg** [comment]
here it is: https://github.com/dominikg/tsconfck/tree/feat/support-solution-style

unfortunately the current "native" implementation also only returns the solution tsconfig, so finding the correct one would need to be done for both parse and parseNative.

**Comment by dominikg** [comment]
added an initial implementation in https://github.com/dominikg/tsconfck/tree/feat/support-solution-style

It includes a pretty crude include pattern to regex approach to find the matching solution where i am not sure if thats exactly how it works inside of typescript but it's a start.

Would love to completely drop using regex there and instead do a single pass character scan, but i need to think about how to properly implement greed for `**/`
