### ISSUE TITLE
feature request: sync version

### ISSUE THREAD

**Issue by privatenumber** [dominikg/tsconfck#31]
**Describe the feature**
Sync API methods.

**A Usecase**
TypeScript loaders (eg. [esbuild-register](https://github.com/egoist/esbuild-register)) that tap into `require()` to transpile the TS file cannot use async methods because `require()` is synchronous.

**Alternatives**
What could be alternative ways to make it happen

**Additional context**

**Comment by dominikg** [comment]
This has been discussed here https://github.com/dominikg/tsconfck/discussions/18 and an initial implementation exists https://github.com/dominikg/tsconfck/tree/feat/sync  

But like i concluded in that discussion, the current state of that isn't great and if sync were added it has to be in a maintainable way.

Would you be interested in sending a PR for this?

Aslo not sure what you are using esbuild-register for but maybe [tsm](https://github.com/lukeed/tsm) or [esmo]( https://github.com/antfu/esno) could be alternatives?

**Comment by privatenumber** [comment]
In ended up moving forward with my own solution. Thank you for your time!

> Aslo not sure what you are using esbuild-register for but maybe [tsm](https://github.com/lukeed/tsm) or [esmo](https://github.com/antfu/esno) could be alternatives?

Neither of them support reading from `tsconfig.json`.
