### ISSUE TITLE
Allow parsing individual "Solution Style" files not named `tsconfig.json`

### ISSUE THREAD

**Issue by medfreeman** [dominikg/tsconfck#34]
## Description

Sometimes "solution style" tsconfig files need to be referenced individually.
An IDE will mostly load a single top-level `tsconfig.json` file that can reference solution files.
However, it is not uncommon to instruct (i.e. build) tooling to load an individual solution file (i.e. tests written in ts need to not end up in `dist` folder).

At the moment, if a path to a tsconfig file not exactly named `tsconfig.json` is passed to `parse` / `parseNative` function, it will go through `resolveTsConfig`, which will instruct an adjacent `tsconfig.json`to be loaded.

**Workaround**: reference a source file instead

That's the reason i filed this as a bug, nothing would make me think that the "root" config would be loaded in place of a possibly valid solution config, from what can be expected from the docs.

## Reproduction

In the linked PR branch, just revert the feature code (that allows any file starting with `tsconfig.` and ending with `.json`) and see the tests fail because they would expect the adjacent `tsconfig.json` to be parsed instead of the referenced individual solution file.
https://github.com/dominikg/tsconfck/pull/35/commits/d3c17a4160698942778fb6ad15cf793542eae489

## Additional Information

For context, i'm using this in a (currently private, soon public) esm project starter which has a script allowing referencing properties of a tsconfig.
Part of the goal of this script is to automatically discover all the source files of a project by passing it the typical `--project tsconfig.build.json`.
Using the workaround, referencing one of the project's source files to have it resolve automatically to `tsconfig.build.json` would defeat the purpose and adds unnecessary processing for a file the end user has already knowledge of.

**PR**: #35

**Comment by dominikg** [comment]
Wow, thanks for this very detailed report and PR, even including additional tests :100: 

Is the tsconfig.something.json naming schema described by typescript somewhere and an actual limitation of solution style configs or do you think .endsWith('.json') would be sufficient too?

**Comment by medfreeman** [comment]
Thanks!
To my knowledge it's not specifically referenced anywhere (c.f. https://www.typescriptlang.org/tsconfig#extends) in docs, the code itself shows no limitation around filenames (no need for the `.json` extension btw), c.f. [findConfigFile](https://github.com/microsoft/TypeScript/blob/55e13e9115b3cc5458d76c39da1211dc28d7b51f/src/compiler/program.ts#L2-L7), [readConfigFile](https://github.com/microsoft/TypeScript/blob/55e13e9115b3cc5458d76c39da1211dc28d7b51f/src/compiler/commandLineParser.ts#L1762-L1769) & [parseConfigFileNameToJson](https://github.com/microsoft/TypeScript/blob/55e13e9115b3cc5458d76c39da1211dc28d7b51f/src/compiler/commandLineParser.ts#L1771-L1782).
I tried building a proper tsconfig file with a random filename, even using `extends` and it works perfectly.

Should i perhaps then remove the filename restriction instead, in accordance to what typescript does?

**Comment by medfreeman** [comment]
In fact there's a reference to this as an example in the typescript repo, referencing `src/tsconfig_base.json` here: https://www.typescriptlang.org/docs/handbook/project-references.html#overall-structure
Not that it implies anything specific though.

**Comment by dominikg** [comment]
Even if typescript technically allows parsing tsconfig json from files not having a .json extension, tsconfck needs something to determine if the filename argument is a config file or a source file. 

So i'd be fine with 
```js
if (path.extname(filename) !== '.json') {
  return;
}
```
in resolveTSConfig and accepting the fact that this won't work for projects using a different extension for their config files 

Otherwise there would have to be an additional option or separate parseWithoutFind exports

**Comment by medfreeman** [comment]
Seems fine!
Changes already made.
Thanks!

**Comment by dominikg** [comment]
released in 1.1.2. Thanks!
