### ISSUE TITLE
`extends` field should allow node_modules references

### ISSUE THREAD

**Issue by aleclarson** [dominikg/tsconfck#71]
**Describe the feature**
The `extends` field might reference a `tsconfig.json` file from an installed dependency.

Current behavior is an error like:
```
TSConfckParseError: failed to resolve "extends"
```

**A Usecase**
Here's a real world example:
https://github.com/unocss/unocss/blob/65355361832c38ef6d8d8bcdac0585fbf7d2adbb/examples/quasar/tsconfig.json#L2

**Comment by dominikg** [comment]
it does, see https://github.com/dominikg/tsconfck/blob/e0ca5b224f01eabe48fda0c6654aed5d2400cb59/tests/fixtures/parse/valid/with_extends/node_fallback/tsconfig.json#L2

under the hood it uses createRequire, so if the package is installed it should be found

**Comment by aleclarson** [comment]
ah ok, it must've not been installed then :)
