### ISSUE TITLE
warning tsconfck@2.0.1: The engine "pnpm" appears to be invalid.

### ISSUE THREAD

**Issue by ehahn9** [dominikg/tsconfck#74]
Hi! I'm using a downstream package (vite-tsconfig-paths@4.0.3) in my project and, yarn now complains thusly:

`warning tsconfck@2.0.1: The engine "pnpm" appears to be invalid.`

The maintainers over there point to [this](https://github.com/dominikg/tsconfck/blob/ddd5d833660b3d966fb63a991733080a3e345e87/package.json#L108) as the culprit. Here's the [thread](https://github.com/aleclarson/vite-tsconfig-paths/issues/88). With apologies, I'm not smart enough track this down myself :-(

Thx

**Comment by dominikg** [comment]
are you using yarn v1? https://github.com/yarnpkg/yarn/issues/7560

this project uses pnpm as it's package manager, other pms should ignore engine constraints not set for themselves. please update yarn or file with your pm
